version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB:dbname
      TZ: "world/time"
      PGTZ: "world/time"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rust-app:
    build:
      context: .
      dockerfile: Dockerfile.rust
    environment:
      DATABASE_URL: postgres://user:password@postgres/dbname
      TZ: "world/time"
    ports:
      - "13389:13389"
    depends_on:
      - postgres

  oracledb-test:
    build:
      context: .
      dockerfile: Dockerfile.oracle
    container_name: oracledb-test
    environment:
      - LD_LIBRARY_PATH=/opt/oracle/instantclient_21_14
    stdin_open: true
    tty: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:

