version: "3.9" # Healthcheck 지원을 위한 버전 업데이트

services:
  postgres:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rust-app:
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.rust
    env_file:
      - .env
    ports:
      - "13389:13389"

  oracledb-test:
    build:
      context: .
      dockerfile: Dockerfile.oracle-test
    container_name: oracledb-test
    environment:
      - LD_LIBRARY_PATH=/opt/oracle/instantclient_21_14
    stdin_open: true
    tty: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
