# 베이스 이미지 설정
FROM rust:latest

# 필요한 패키지 설치
RUN apt-get update && apt-get install -y libaio1 unzip wget

# Oracle Instant Client 설치
RUN mkdir -p /opt/oracle \
    && cd /opt/oracle \
    && wget https://download.oracle.com/otn_software/linux/instantclient/2114000/instantclient-basic-linux.x64-21.14.0.0.0dbru.zip -O /tmp/instantclient-basic-linux.x64-21.14.0.0.0dbru.zip \
    && unzip /tmp/instantclient-basic-linux.x64-21.14.0.0.0dbru.zip -d /opt/oracle \
    && rm /tmp/instantclient-basic-linux.x64-21.14.0.0.0dbru.zip
ENV LD_LIBRARY_PATH=/opt/oracle/instantclient_21_14

# 프로젝트 디렉토리로 이동
WORKDIR /usr/src/app

# 전체 소스 파일 복사
COPY . .

# 종속성 빌드
RUN cargo build --release

# 포트 설정
EXPOSE 13389

# 실행 명령어 설정
CMD ["cargo", "run", "--release", "--bin", "test"]

