[package]
name = "rshash"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
structopt = "0.3"
tokio = { version = "1", features = ["full"] }
clap = { version = "3.0.0", features = ["derive"] }
